version: '2.4'
services:
  server:
    build: .
    entrypoint:
      - node
      - server.js
    tty: true
    stdin_open: true
    ports:
      - '50051:50051'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
